plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nemerpus.hondaassistbridge'
    compileSdk 36

    defaultConfig {
        applicationId 'com.nemerpus.hondaassistbridge'
        minSdk 26
        targetSdk 36
        versionCode 20
        versionName '0.12.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
